### PR TITLE
fix find_tool and find_vs_version might returns incompatible values

### PR DESCRIPTION
**Pull request by Speedy37**
On my PC, I have both MSVC 15 and 16 and found out that find_vs_version returns MSVC 16 while find_tool return MSVC 15 linker.

This caused rust to use MSVC 15 linker, while cmake generated file where made with MSVC 16.

### CODE REVIEW

**Comment by Speedy37** [comment]
Maybe a better approach to find the latest version would be to implement something like: https://github.com/microsoft/vswhere/blob/f078b21784b53dd811ad72f0334b7b70f22aa9cf/src/vswhere.lib/InstanceSelector.cpp#L34

**Comment by alexcrichton** [comment]
Thanks for this! I agree though yeah if we're doing comparisons we should probably do some pattern matching here, because otherwise I think this is doing lexicographical ordering which isn't numerical ordering? (or semver ordering)

**Comment by Speedy37** [comment]
I now convert installation version to Vec<u16> for the ordering.

**Comment by alexcrichton** [comment]
Nice!

**Pull request merged**
