### PR TITLE
Default to emcc for wasm32-unknown-unknown if it's available on the $PATH.

### PR DESCRIPTION
**Pull request by dot-asm**
On related note one can make a case for forcing `-ffreestanding` on the unknown target to ensure that emcc doesn't have ideas about using emscripten run-time...

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR here, but AFAIK emscripten isn't compatible with wasm32-unknown-unknown, so I'm not sure if this would work. Does this work for a project for you locally?

**Comment by dot-asm** [comment]
> Does this work for a project for you locally?

Yes. For now I do it by setting `CC` environment variable to `emcc` and `AR` to `emar`. It might happen that it depends on the fact that our C library doesn't have any dependencies on the C run-time, by its design. I even compile with `-fno-builtin` to ensure that compiler doesn't slip in C run-time calls behind the curtains. For reference, `-ffreestanding` is kind of a "stronger" version of `-fno-builtin`. Well, standalone C code is probably not as common place as this PR implies, which means that it would probably be more appropriate to stick to setting `CC` and `AR`...

**Comment by dot-asm** [comment]
> Well, standalone C code is probably not as common place as this PR implies

On the other hand, I wonder what are the real-life expectations? Is it actually so that most of the stock C libraries can be compiled for wasm32-unknown-unknown with stock clang? What I'm trying to say is that if there is **working** C code that works with wasm32-unknown-unknown Rust target, is it possible that it can't have dependencies on C run-time?

Just in case for reference. The reason for all this it that we do have some `#include <std*.h>` for type definitions, which is problematic with stock `clang --target=wasm32`. ..

**Comment by dot-asm** [comment]
> can be compiled ... with stock clang?

It's kind of a slippery question, isn't it? I mean it's not necessarily exclusively about "stock clang", but about what you call and link with... Either way, the point I'm trying to make is that if the only thing that actually works is standalone C, then it doesn't matter which compiler do you use...

**Comment by dot-asm** [comment]
OK, after further consideration I would agree that it might be less appropriate to default to `emcc`... It still might be helpful to fall back to `emcc` **if** clang doesn't recognize `--target=wasm32`. Or rather try to fall back, because it will still be tested for availability on the `$PATH`... Should I pursue this? Or should we just close this? :-)

**Comment by dot-asm** [comment]
I consider the lack of response as "close." But before I do, I wonder following. Formally speaking using system `ar` is not guaranteed to work with arbitrary binary formats(*), such as binary wasm32. One can make a case for querying `clang -print-search-dirs` and checking for availability of `llvm-ar` on the programs path. Actually, one can make the case for using llvm-ar in **all** clang cases, which should ensure that cross-compilations work smoothly...

(*) Well, `ar` can archive arbitrary files, but it can be ar's responsibility to maintain common name lookup table, which is binary-executable-format-specific.

**Comment by alexcrichton** [comment]
AFAIK the `wasm32-unknown-unknown` Rust target has no equivalent with a C toolchain right now. It's akin to a "kernel" target on native platorms where there is nothing to import from the environment so the C headers are theoretically possible but must bring everything, including the allocator. This doesn't really work out well because there's no established libc, so I'm hesitant to support this because while it may work for your specific use case I feel that C support for `wasm32-unknown-unknown` is never going to work out "in the large"

**Comment by dot-asm** [comment]
> It's akin to a "kernel" target on native platorms

Right, hence the suggestion to forcing `-ffreestanding`.

**Pull request closed without merging**
