### PR TITLE
Use xcrun-rs for iOS SDK detection.

### PR DESCRIPTION
**Pull request by luxxxxy**
Use the [xcrun](https://crates.io/crates/xcrun) crate for detecting the iOS SDK.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Could you elaborate a bit on the rationale for this change though? I see that the crate was created a few hours before this PR, so I'm not sure what there is to gain by using this as a dependency vs what's there today

**Comment by luxxxxy** [comment]
I ended up making the crate because I thought it'd be useful for my project ([Crabapple](https://github.com/Crabapple-iOS/crabapple)) and remembered that this crate also used xcrun.

I simply thought it'd lead to neater code, and could be used for other iOS/macOS related stuff in the future (such as automatically finding the tools such as `clang` that are included with the SDK)

**Comment by alexcrichton** [comment]
Ah ok, in that case I think I'd prefer to leave this as-is for now. If the need arises I think it may make sense to look into an external crate but for now this is simple enough I think it's ok to have inline.

**Comment by luxxxxy** [comment]
Understandable.

**Pull request closed without merging**
