### PR TITLE
use wr-c++ instead of vx-cxx

### PR DESCRIPTION
**Pull request by BaoshanPang**
We decide to use the name "wr-c++" for the compiler driver.

### CODE REVIEW

**Comment by BaoshanPang** [comment]
@alexcrichton 

Thanks for approved and merged the code.
Can you help to label it so we can pick it up with "cargo update"?

Thanks,
Baoshan

**Comment by alexcrichton** [comment]
Sure thing, done!

**Comment by BaoshanPang** [comment]
@alexcrichton 

Appreciate your quick response.
But I made a big mistake, I typed "wr-c++" to "wr=c++", I need to create a new PR to fix it.
I am very sorry to bother you again.

Thanks,
Baoshan

**Comment by BaoshanPang** [comment]
@alexcrichton 

Actually the code in my  branch is correct, but the commit "https://github.com/alexcrichton/cc-rs/commit/0187762febae2ea8676e9b06f96f07f650013219" changed "wr-c++" to "wr=c++" for some reason.

Can you help to fix it?

Thanks,
Baoshan

**Comment by alexcrichton** [comment]
Oops my bad, I typo'd the merge there

**Comment by alexcrichton** [comment]
(published a fixed version)

**Comment by BaoshanPang** [comment]
Thanks!

**Pull request merged**
