### PR TITLE
Avoid flag conflicts and allow default flag generation to be disabled

### PR DESCRIPTION
**Pull request by GeorgeHahn**
This PR addresses https://github.com/alexcrichton/cc-rs/issues/309 and https://github.com/alexcrichton/cc-rs/issues/371.

The default flags may not be appropriate for all possible cross-compiling scenarios. Many flag conflicts can be caught automatically by checking `CFLAGS`/`CXXFLAGS` and disabling default flags if necessary. Some conflicts may not be caught automatically - to address this, an environment variable is added to disable default flags. This variable is (arbitrarily named & quickly chosen) `CRATE_CC_NO_DEFAULTS`.

A special case is added for optimization flags. No optimization flag is added if one is set in `CFLAGS`/`CXXFLAGS`. With the current implementation/code organization, an optimization flag is not added when default flags are disabled.

This is a first pass - I'll address changes & rebase as necessary.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! 

Thinking about this again and seeing the recent opening of https://github.com/alexcrichton/cc-rs/issues/376, it actually reminds me that I wonder if we could solve this by simply placing user-defined arguments at the end of the CLI instead of the front? I thought that was what `cc` already!

I don't think that strategy would solve #371, but I think it would solve your use case and #376 I thinkg? (afaik C compilers always prefer later CLI flags)

**Comment by GeorgeHahn** [comment]
In our case, the consuming crate sets `-werror`; this causes the conflicting `-march` flags to fail the build. I agree that user defined flags should be at the end - I'll make that change here.

The `-werror` case requires either a strategy for automatic conflict handling or a configurable option to disable default flags. This PR implements a fairly simple conflict handling strategy, but there are definitely other options.

**Comment by GeorgeHahn** [comment]
69940e0a389f0a7e7da7474e12ac2560af93acb3 inserts user defined flags after default flags but before flags specified by the dependent crate. This minimizes the amount of change while still solving #376.

Inserting the user's flags after the dependent crate's flags would require further re-ordering. I'm not certain about the level of impact, but I think that would belong in a separate PR and may deserve a new minor version.

**Comment by alexcrichton** [comment]
I'm curious, is the explicit checking for `-O` and such flags still necessary if flags are placed at the end? I was under the impression that later optimization settings always override previous ones, similarly for target configuration.

**Comment by GeorgeHahn** [comment]
Duplicate optimization flags shouldn't impact gcc/clang, but may impact MSVC ([ref](https://docs.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=vs-2017)).

Duplicate target related flags (in my case, the `-march` flag) can give a warn level message that turns into an error if the consumer crate sets `-werror`.

**Comment by alexcrichton** [comment]
Ok!

**Comment by fanzeyi** [comment]
:( This change is breaking our build system since we are passing some flags in `CFLAGS` that are starting with `-m` while not doing cross-compiling. Can we please have an environment variable to tell cc skip these checks?

**Comment by alexcrichton** [comment]
Ok I've turned off the automatic inference of turning off defaults in https://github.com/alexcrichton/cc-rs/commit/3d0abff4846a14d9770230d7790b4b4ab3ddbf6a, sorry for the breakage!

**Pull request merged**
