### PR TITLE
Use clang for target android

### PR DESCRIPTION
**Pull request by edelangh**
android ndk r18 remove gnu support, we should use clang instead of gcc

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! In order to keep supporting older SDKs though (which rust-lang/rust may be using?) could this default to using clang but use gcc as a fallback if it's not detected?

**Comment by edelangh** [comment]
I've updated my commit.
It will check for gnu first as it always has done

**Comment by alexcrichton** [comment]
Thanks! Could the rustfmt changes be left for a later time as well? Additionally, could the logic of replacing strings in the target be deduplicated between the gcc/clang case?

**Comment by edelangh** [comment]
Ok sorry for fmt, I used `git add -u` because of time :/
Thank you for seeing the duplication, everything should be right now

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
